# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beer', '0004_beer_image_tile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Burger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('review', models.CharField(max_length=5000)),
                ('grade', models.CharField(max_length=1)),
                ('image', models.CharField(max_length=100)),
                ('image_tile', models.CharField(max_length=100)),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beer.Manufacturer')),
            ],
        ),
    ]
