# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='burger',
            old_name='grade',
            new_name='grade_total',
        ),
        migrations.AddField(
            model_name='burger',
            name='grade_appearance',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='burger',
            name='grade_taste',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='burger',
            name='juicyness',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='burger',
            name='spicyness',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
    ]
