# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 17:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('review', models.CharField(max_length=5000)),
                ('grade_taste', models.CharField(max_length=1)),
                ('grade_color', models.CharField(max_length=1)),
                ('grade_smell', models.CharField(max_length=1)),
                ('grade_smoothness', models.CharField(max_length=1)),
                ('grade_foam', models.CharField(max_length=1)),
                ('grade_total', models.CharField(max_length=1)),
                ('alc', models.CharField(max_length=4)),
                ('image', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=10)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Burger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('grade', models.CharField(max_length=1)),
                ('review', models.CharField(max_length=5000)),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beer.Country')),
            ],
        ),
        migrations.AddField(
            model_name='burger',
            name='maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beer.Manufacturer'),
        ),
        migrations.AddField(
            model_name='beer',
            name='brewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beer.Manufacturer'),
        ),
    ]
