# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='beer_type',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
