# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 11:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0002_beer_beer_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='burger',
            name='maker',
        ),
        migrations.DeleteModel(
            name='Burger',
        ),
    ]
