# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0003_auto_20170427_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='image_tile',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
